---
- name: Automating cse356 hw0
  hosts: hw1
  become: true

  tasks:
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true

    - name: Install git
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: true

    - name: Clean the directory /var/www/html
      ansible.builtin.file:
        path: /var/www/html/
        state: absent

    - name: Insert files from git to /var/www/html
      ansible.builtin.git:
        repo: https://github.com/Danieljlee42/cse356_hw1.git
        dest: /var/www/html/
        update: false

    - name: Update nginx configuration file
      ansible.builtin.lineinfile:
        path: "/etc/nginx/sites-available/default"
        regexp: "index index.html index.htm index.nginx-debian.html;"
        line: "index hw0.html index.html index.htm;"
        backrefs: true

    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
